### ISSUE TITLE
MoreWaita not used

### ISSUE THREAD

**Issue by melomane63** [taiwbi/gnome-accent-directories#1]
MoreWaita is installed but not used

in index.theme :

Inherits=Adwaita,MoreWaita,AdwaitaLegacy,hicolor
but must be:
Inherits=MoreWaita,Adwaita,AdwaitaLegacy,hicolor

**Comment by taiwbi** [comment]
You're right! Thank you for mentioning it.  
It's fixed in the `dev` branch #803e5a63166aee3656cb370a574506813e9544bc and will be published in the next release.

**Comment by melomane63** [comment]
Ok, thank you! It is time ti close this issue.

**Comment by melomane63** [comment]
Closed
