### ISSUE TITLE
Nautilus color icon yellow is not good in dev branch

### ISSUE THREAD

**Issue by melomane63** [taiwbi/gnome-accent-directories#2]
color used is #B49800 but gnome color is #C88800

**Comment by taiwbi** [comment]
None of the nautilus colored icon are exactly the same as accent color (except blue). I think it look better now though!

**Comment by melomane63** [comment]
yes, all new icons are very pretty and consistent, apart from yellow nautilus. 
on the left , actually , on the right mod icon set to same color as folder #C88800 ; 
of course, color is always subjective!
![Capture d’écran du 2024-11-25 09-08-39](https://github.com/user-attachments/assets/82e92492-5b1e-47f9-8aee-ed5e7a981816)

**Comment by taiwbi** [comment]
Maybe you're right about yellow one! I MIGHT change its color later but for now the new version is already under review in [GNOME store](https://extensions.gnome.org/review/60716)
