### ISSUE TITLE
Apply accents to gtk3 apps and flatpaks. 

### ISSUE THREAD

**Issue by melomane63** [taiwbi/gnome-accent-directories#3]
Gnome change accent to shell and libwaita apps and flatpaks, but not to GTK3 apps and flatpaks. 

i have made bash script and add 2 lines to your extension, and it work flaweless. 

I don't personally need this done, but it could be a very useful option for others peoples. 
Here's the code:

// onAccentColorChanged  Run external script
const ScriptPath = GLib.get_home_dir() + "/.local/share/gnome-shell/extensions/accent-directories@taiwbi.com/script.sh";
GLib.spawn_command_line_async(ScriptPath);

######script.sh

#!/bin/bash

GTKCSS=$HOME/.config/gtk-3.0/gtk.css

ACCENT=`gsettings get org.gnome.desktop.interface accent-color`

if [ "$ACCENT" = "'blue'" ]
then
    rm -f $GTKCSS  && flatpak override --user --nofilesystem=xdg-config/gtk-3.0

elif [ "$ACCENT" = "'teal'" ]
then
    rm $GTKCSS -f &&  echo '@define-color accent_color #8DC6D0;' >> $GTKCSS  && echo '@define-color accent_bg_color #2190A4;' >> $GTKCSS && flatpak override --user --filesystem=xdg-config/gtk-3.0:ro

elif [ "$ACCENT" = "'green'" ]
then
    rm $GTKCSS -f && echo '@define-color accent_color #9AC8A2;' >> $GTKCSS  && echo '@define-color accent_bg_color #3A944A;' >> $GTKCSS  && flatpak override --user --filesystem=xdg-config/gtk-3.0:ro

elif [ "$ACCENT" = "'yellow'" ]
then
    rm $GTKCSS -f &&  echo '@define-color accent_color #E2C27C;' >> $GTKCSS  && echo '@define-color accent_bg_color #C88800;' >> $GTKCSS && flatpak override --user --filesystem=xdg-config/gtk-3.0:ro

elif [ "$ACCENT" = "'orange'" ]
then
    rm $GTKCSS -f &&  echo '@define-color accent_color #F5AB7C;' >> $GTKCSS  && echo '@define-color accent_bg_color #ED5B00;' >> $GTKCSS && flatpak override --user --filesystem=xdg-config/gtk-3.0:ro

elif [ "$ACCENT" = "'red'" ]
then
    rm $GTKCSS -f &&  echo '@define-color accent_color #F2939E;' >> $GTKCSS  && echo '@define-color accent_bg_color #E62D42;' >> $GTKCSS && flatpak override --user --filesystem=xdg-config/gtk-3.0:ro

elif [ "$ACCENT" = "'pink'" ]
then
    rm $GTKCSS -f &&  echo '@define-color accent_color #E9AECA;' >> $GTKCSS  && echo '@define-color accent_bg_color #D56199;' >> $GTKCSS && flatpak override --user --filesystem=xdg-config/gtk-3.0:ro

elif [ "$ACCENT" = "'purple'" ]
then
    rm $GTKCSS -f &&  echo '@define-color accent_color #C69ED4;' >> $GTKCSS  && echo '@define-color accent_bg_color #9141AC;' >> $GTKCSS && flatpak override --user --filesystem=xdg-config/gtk-3.0:ro

elif [ "$ACCENT" = "'slate'" ]
then
    rm $GTKCSS -f &&  echo '@define-color accent_color #B5BFC9;' >> $GTKCSS  && echo '@define-color accent_bg_color #6F8396;' >> $GTKCSS && flatpak override --user --filesystem=xdg-config/gtk-3.0:ro

fi

**Comment by taiwbi** [comment]
Although I appreciate your work, and it is indeed a valuable feature, it might be better suited for a different extension. This extension is intended to change icon colors based on the GNOME accent color.

Plus, not only is this approach not a clean way of achieving that, but it also overrides any user's custom style in the `gtk-3.0.css` file. Also, publishing an extension on the [GNOME Store](https://extensions.gnome.org) is not permitted if it relies on external scripts or binaries.
