### ISSUE TITLE
Error: GSettings schema org.gnome.shell.extensions.accent-directories not found

### ISSUE THREAD

**Issue by melomane63** [taiwbi/gnome-accent-directories#4]
After update to V1.2 , extension not work.  remove  ans reinstall, no luck. Fedora 41 

Error: GSettings schema org.gnome.shell.extensions.accent-directories not found

Stack trace:
  _init@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:755:23
  fillPreferencesWindow@file:///home/domenicoguerra/.local/share/gnome-shell/extensions/accent-directories@taiwbi.com/prefs.js:23:29
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:39:24
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:24:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:15:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:138:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34

**Comment by taiwbi** [comment]
Oops :(
